[build]
    functions = "functions"
    external_node_modules = ["express","axios", "pandadoc-node-client", "@aws-sdk/client-s3", "cookie-parser" , "dotenv", "multer",  "serverless-http","@aws-sdk/s3-request-presigner",]

[functions]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"